language: ruby
addons:
  apt:
    sources:
    - precise-pgdg-9.5
    packages:
    - postgresql-9.5
    - postgresql-contrib-9.5  
  postgresql: "9.5"
before_script:
  - psql -c 'create database dabbleme_test;' -U postgres