env:
  RUBY_VERSION: 2.7.1
  BUNDLER_VERSION: 1.17.2
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
  POSTGRES_DB: postgres

name: Ruby

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: set environment variables
        uses: allenevans/set-env@v1.0.0
        with:
          overwrite: false
      - uses: actions/checkout@v1

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
        
      - name: Install dependent libraries
        run: sudo apt-get install libpq-dev

      - name: Bundle install
        run: |
          gem install bundler:${{ env.BUNDLER_VERSION }}
          bundle install --jobs 4 --retry 3
      - name: Create database
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          RAILS_ENV: test        
        run: |
          bundler exec rails db:create RAILS_ENV=test
          bundler exec rails db:migrate RAILS_ENV=test
      - name: Run tests
        run: |
          bundler exec rake
      - name: Upload coverage results    
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: coverage-report
          path: coverage        
